variable "subnet_ids" {}
variable "tags" {}
variable "env" {}
variable "vpc_id" {}
variable "sg_port" {}
variable "ssh_ingress" {}
variable "engine_family" {}
variable "engine" {}
variable "engine_version" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "skip_final_snapshot" {}
variable "instance_count" {}
variable "instance_class" {}